# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-113341784-1"

# UI configs
title: "Photography by Vishnu"
subtitle: "See the world through my eyes!"
author: "Vishnu"
header:
 title: "Photography"
 subtitle: "by Vishnu"
footer:
 name: "Hey there, my name is Vishnu"
 bio: "I am a Sailor, I love dogs, mother nature, web-dev, coding and now learning photography."
 github: "Thankyou Github for providing me this platform ;)"
web_design: "VR"
social_urls:
  facebook: "https://www.facebook.com/vishnu.raveendranathan"
  twitter: "https://www.twitter.com/vishnu-raveendranathan"
  instagram: "https://www.instagram.com/capt.vishnu"
  linkedin: "https://in.linkedin.com/in/vishnu-raveendranathan-1b3b9496"
  github: "https://www.github.com/captv89"